import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="logo">
            OFOTD
          </div>
          <nav>
            <ul>
              <li><a href="/product">PRODUCT</a></li>
            </ul>
          </nav>
        </header>
        {children}
        
      </body>
    </html>
  );
}
